config/routes.rb
Rails.application.routes.draw do
  root 'login#login'
  post 'login', to: 'login#logincheck'
  post 'new_acc', to: 'login#new_acc'

  get 'homepage', to: 'home#homepage'
  post 'new_lst', to: 'home#new_lst'
  get 'del_lst', to: 'home#del_lst'

  get 'listview', to: 'listview#listview'
  post 'new_prod', to: 'listview#new_prod'
  get 'del_prod', to: 'listview#del_prod'
  get 'change_prods', to: 'listview#change_prods'

  get 'contact', to: 'contact#contact'
  post 'sendmessage', to: 'contact#sendmessage'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def list_params # Strong parameters for list objects
    params.permit(:name, :list_id)
  end

  def new_lst # Method for creating new lists
    if List.user(session[:user_id]).where(name: list_params[:name]).exists? # If the user already has a list of the same name, then we display a relevant message
      redirect_to homepage_path alert: t('.homepage.existing', name: params[:name])
    else # If there is no pre-existing list, then we create one
      user = User.find(session[:user_id])
      List.create(name: list_params[:name], user: user)
      redirect_to homepage_path
    end
  end

  def del_lst # Method for deleting a list
    List.destroy(list_params[:list_id]) unless List.find(list_params[:list_id]).blank? # If the list_id is not blank, then we delete the relevant list
    redirect_to homepage_path
  end

  def homepage # Method for displaying home page
    if session[:user_id].nil? # If we have no session variable for the user_id, then the user has not signed in
      redirect_to root_path # Redirect back to the login page
    else # Otherwise, we go ahead set the correct variables and show the homepage view
      user = User.find(session[:user_id])
      @user_id = user.id

      @username = user.name
      @pagename = t('.page_title')
    end
  end
end

app/views/home/homepage.html.haml
%br
%br

-# Display each list object with relevant options
- List.user(@user_id).each do |list|
  .listCon
    %p{class: "text"}= list.name
    .listButtons
      = form_tag listview_path, method: 'get' do
        =hidden_field_tag :list_id, list.id
        %input{type: "submit", value: t('.view'), class: "button1"}

      = button_tag(class: "iconButton", onclick: "removeList(" + String(list.id) + ", this)") do
        %i.fas.fa-trash

%br
%br

-# Flash message
= content_tag :div, content_tag(:p, params[:alert], class: "text"), id: "#{"alert"}"

-# Form for creating an new list
= form_tag new_lst_path, method: 'post', id: "newListForm", remote: true do
  = text_field_tag :name, "", class: "inputText", placeholder: t('.new'), oninput: "newListCheck(this)"
  %input{type: "submit", value: t('.add'), class: "button1", id: "newListSubmit", disabled: ""}

%br
%br
%br

-# Button to go to the contact us page
= form_tag contact_path, method: 'get' do
  %input{type: "submit", value: t('.contact'), class: "button1"}

%br
%br

-# Button to go back to login page
= form_tag root_path, method: 'get' do
  %input{type: "submit", value: t('.logout'), class: "button1"}