config/routes.rb
Rails.application.routes.draw do
  root 'login#login'
  post 'login', to: 'login#logincheck'
  post 'new_acc', to: 'login#new_acc'

  get 'homepage', to: 'home#homepage'
  post 'new_lst', to: 'home#new_lst'
  get 'del_lst', to: 'home#del_lst'

  get 'listview', to: 'listview#listview'
  post 'new_prod', to: 'listview#new_prod'
  get 'del_prod', to: 'listview#del_prod'
  get 'change_prods', to: 'listview#change_prods'

  get 'contact', to: 'contact#contact'
  post 'sendmessage', to: 'contact#sendmessage'
end

app/controllers/login_controller.rb
class LoginController < ApplicationController

  def login_params # Strong parameters for list objects
    params.permit(:name, :email, :password)
  end

  def login # Method for login page view
  end

  def logincheck # Here we check if the login info is correct
    if login_params[:email].blank? || login_params[:password].blank? # If the user left any fields blank, then we redirect back to the login page and display a relevant message
      redirect_to root_path, alert: t('.login.blank')
    elsif User.where(email: login_params[:email], password: login_params[:password]).exists? # If we can find a user with a matching email and password
      session[:user_id] = User.find_by(email: login_params[:email]).id # Then we set the user_id session variable and then go to the homepage
      redirect_to homepage_path
    else # If we cannot find a matching user, then we redirect back to the login page and display the appropriate alert
    redirect_to root_path, alert: t('.login.incorrect')
    end
  end

  def new_acc # Method for handling creation of a new account
    if login_params[:email].blank? || login_params[:name].blank? || login_params[:password].blank? # If the user left fields blank, then we redirect to login page with a message
      redirect_to root_path, alert: t('.login.blank')
    elsif User.where(email: login_params[:email]).exists? # If the email is already taken, then redirect back to login page with the appropriate message
      redirect_to root_path, alert: t('.login.in_use')
    elsif login_params[:email] =~ URI::MailTo::EMAIL_REGEXP # If the email matches the standard email regex, then we create the account, and set the session variable
      session[:user_id] = User.create(email: login_params[:email], name: login_params[:name], password: login_params[:password]).id
      redirect_to homepage_path
    else # Otherwise the email was in an invalid faormat, so we go back to the login page and display a message
    redirect_to root_path, alert: t('.login.invalid')
    end
  end
end

app/views/login/login.html.haml
%h1{class: "mainTitle"}= t('.title')
%br

-# Buttons to toggle the login form and the new account form
.login
  .loginOptions
    %button.button1#loginButton{onclick: "showLoginForm();"}= t('.login_button')
    %button.button1#createButton{onclick: "showCreateForm();"}= t('.new_acc')

  %br

  -# Flash message
  - flash.each do |key, value|
    = content_tag :div, content_tag(:p, value, class: "text"), id: "#{key}" unless value.blank?

  -# Login in form with relevant validation
  = form_tag login_path, method: 'post', id: "loginForm", class: "loginForm" do
    = email_field_tag :email, "", required: true, class: "inputText", placeholder: t('.email')
    %br
    = password_field_tag :password, "", required: true, class: "inputText", placeholder: t('.password')
    %br
    %br
    %input.button1{type: "submit", value: t('.sign_in')}

  -# New account form with relevant validation
  = form_tag new_acc_path, method: 'post', id: "createForm", style: "display: none", class: "loginForm" do
    = text_field_tag :name, "", required: true, class: "inputText", placeholder: t('.name')
    %br
    = email_field_tag :email, "", required: true, class: "inputText", placeholder: t('.email')
    %br
    = password_field_tag :password, "", required: true, class: "inputText", placeholder: t('.password')
    %br
    %br
    %input.button1{type: "submit", value: t('.new_acc')}