config/routes.rb
Rails.application.routes.draw do
  root 'login#login'
  post 'login', to: 'login#logincheck'
  post 'new_acc', to: 'login#new_acc'

  get 'homepage', to: 'home#homepage'
  post 'new_lst', to: 'home#new_lst'
  get 'del_lst', to: 'home#del_lst'

  get 'listview', to: 'listview#listview'
  post 'new_prod', to: 'listview#new_prod'
  get 'del_prod', to: 'listview#del_prod'
  get 'change_prods', to: 'listview#change_prods'

  get 'contact', to: 'contact#contact'
  post 'sendmessage', to: 'contact#sendmessage'
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def contact_params # Strong parameters for contact page
    params.permit(:email, :message)
  end

  def contact # Display the contact view
    if session[:user_id].blank? # If we have no session variable for the user_id, then the user has not signed in
      redirect_to root_path
    else # Otherwise, we set up the variables relevant to the page
      @username = User.find(session[:user_id]).name
      @pagename = t('.page_title')
      @email = User.find(session[:user_id]).email
    end
  end

  def sendmessage # Method for sending the message
    if contact_params[:email].blank? # If the email was blank, then stay on page and display a flash alert
      flash[:alert] = t('.contact.blank_email')
      redirect_to contact_path
    elsif contact_params[:message].blank? # If the message is blank, then stay on the page and display a flash alert
      flash[:alert] = t('.contact.blank_message')
      redirect_to contact_path
    elsif contact_params[:email] =~ URI::MailTo::EMAIL_REGEXP # If the email is in the correct format, then we send the message and go to home page
      ContactMailer.contact_email(contact_params[:email], contact_params[:message]).deliver_now
      redirect_to homepage_path
    else # Otherwise stay on page and display a flash alert
      flash[:alert] = t('.contact.invalid')
      redirect_to contact_path
    end
  end
end

app/views/contact/contact.html.haml
-# Flash message
- flash.each do |key, value|
  = content_tag :div, content_tag(:p, value, class: "text"), id: "#{key}" unless value.blank?

-#Contact page email/message form with appropriate validation
= form_tag sendmessage_path, method: 'post' do

  = email_field_tag :email, @email, required: true, pattern: "[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$", class: "inputText", placeholder: t('.email')
  %br
  = text_area_tag :message, "", required: true, class: "inputText", placeholder: t('.message')
  %br
  %input{type: "submit", value: t('.send'), class: "button1"}

  %br
  %br

-#Button to take user back to home page
= form_tag homepage_path, method: 'get' do
  %input{type: "submit", value: t('.back'), class: "button1"}